"""init

Revision ID: a9549b3001b5
Revises: 
Create Date: 2024-03-12 13:28:25.618068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9549b3001b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dealer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dealer_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dealer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dealer_name'))

    op.drop_table('dealer')
    # ### end Alembic commands ###
